{
    "Service": "/zlabiamdk/Services/mymbt.service",
    "DefiningRequests": [{
        "Name": "Customers",
        "Query": "Customers"
    }],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/zlabiamdk/Actions/mymbt/Service/SyncFailureMessage.action",
    "OnSuccess": "/zlabiamdk/Rules/mymbt/ErrorArchive_CheckForSyncError.js"
}